In [1]:
import cv2
import numpy as np
cv2.__version__

'4.1.2'

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
img = cv2.imread("/cog-tr1_t.jpg")
img2 = img.copy()

In [6]:
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
cv2.imwrite("/cog-tr1_t_mod.jpg", gray)

True

In [7]:
gray2 = cv2.bitwise_not(gray)
cv2.imwrite("/cog-tr1_t_mod2.jpg", gray2)

True

In [8]:
lines = cv2.HoughLinesP(gray2, rho=1, theta=np.pi/360, threshold=80, minLineLength=30, maxLineGap=5)
print(lines)

[[[  0   9 292 301]]

 [[  0 288 288   0]]

 [[  0  22 279 301]]

 ...

 [[  0 243  59 301]]

 [[222  16 278  72]]

 [[257   0 301  44]]]


In [9]:
print(len(lines))

356


In [10]:
for line in lines:
    x1, y1, x2, y2 = line[0]

    # 赤線を引く
    red_line_img = cv2.line(img2, (x1,y1), (x2,y2), (0,0,255), 3)
    cv2.imwrite("/cog-tr1_t_red.jpg", red_line_img)